### PR TITLE
fix: Fix statuscode 0 on compliant last file

### LINKED ISSUE #12: go-licenser -d exits 0 on missing header
> -d	skips rewriting files and returns exitcode 1 if any discrepancies are found.

It is logging that the files are missing a header but it is not setting the exit code. I think it is only reporting the exit code for the last scanned file.

### PR DESCRIPTION
**Pull request by marclop**
This change fixes a bug where even if multiple files where missing the
license header if the last file on the walked tree does have a license
header the statuscode was overwritten to 0.

Resolves #12

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -129,19 +129,29 @@ func reportFile(out io.Writer, f string) {
...
 		}
 
 		if info.IsDir() && stringInSlice(info.Name(), exclude) {
 			return filepath.SkipDir
 		}
+		c, e := addOrCheckLicense(path, ext, info, dry, out)
+		if c > 0 {
+			code = c
+		}
+		if err != nil {
```
Comment (andrewkroh) [inline main.go]: IIUC this could lead to a case where the returned `error` value is unrelated to the error code. Is that something you want?

I think it would be easier to reason about if there were only a single value indicating that an error occurred, but it's a slightly bigger change. You could have an `error` type that has an `ExitCode()` method. For example:

```
type exitCoder interface {
    ExitCode() int
}

type exitError struct {
    exitCode int
    cause error
}

func (e exitError) Error() string { ... }
func (e exitError) ExitCode() int { return e.exitCode }

// exitStatus is determines what status to set when the process exits.
func exitStatus(err error) int {
  // if err == nil return 0
  // if err implements exitCoder return exitCode()
  // else return non-zero
}

func main() {
  ...
  os.Exit(exitStatus(err))
}
```

Comment (marclop) [reply main.go]: I had already thought about it but didn't bother going about that route since it meant making it a bigger change, but it might make sense to do that.

**Comment by marclop** [comment]
@andrewkroh implemented your suggestions in https://github.com/elastic/go-licenser/pull/13/commits/5851cf2eb2d03cc496f75dc89f49e433c6733d1f
